name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  check-base-url:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Building app
      run: npm run build

    - name: Check if baseUrl includes localhost
      id: check_base_url
      run: node check-base-url.js
      continue-on-error: true

    - name: Proceed if baseUrl is valid
      if: ${{ steps.check_base_url.outcome == 'success' }}
      run: echo "Proceeding with the workflow..."

    - name: Fail if baseUrl includes localhost
      if: ${{ steps.check_base_url.outcome != 'success' }}
      run: echo "baseUrl includes localhost. Failing the job." && exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: check-base-url
    if: ${{ steps.check_base_url.outcome == 'success' }}  # Only deploy if the CI checks pass
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Kali Linux
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # Make sure to add this secret in GitHub
      run: |
        echo "$SSH_PASSWORD" | sshpass ssh grayhat@192.168.2.114 "
          cd /var/www/myapp/CICD-Project && 
          git pull origin main && 
          npm install && 
          npm run build && 
          sudo systemctl restart nginx  # Restart Nginx server
        "
