name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check-base-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Check if baseUrl includes localhost
      id: check_base_url
      run: node check-base-url.js
      continue-on-error: true

    - name: Proceed if baseUrl is valid
      if: ${{ steps.check_base_url.outcome == 'success' }}
      run: echo "Proceeding with the workflow..."

    - name: Fail if baseUrl includes localhost
      if: ${{ steps.check_base_url.outcome != 'success' }}
      run: echo "baseUrl includes localhost. Failing the job." && exit 1
