name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  check-base-url:
    runs-on: ubuntu-latest
    outputs:
      base_url_success: ${{ steps.check_base_url.outcome }}  # Set output based on step outcome
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Building app
        run: npm run build

      - name: Check if baseUrl includes localhost
        id: check_base_url
        run: node check-base-url.js
        continue-on-error: true

      - name: Proceed if baseUrl is valid
        if: ${{ steps.check_base_url.outcome == 'success' }}
        run: echo "Proceeding with the workflow..."

      - name: Fail if baseUrl includes localhost
        if: ${{ steps.check_base_url.outcome != 'success' }}
        run: echo "baseUrl includes localhost. Failing the job." && exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: check-base-url
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kali Linux
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 192.168.2.114  # Kali machine IP
          username: grayhat    # Your Kali machine username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Private key in GitHub secrets
          port: 22
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  # If your private key is encrypted
          script: |
            cd /var/www/myapp/CICD-Project &&
            git pull origin main &&
            npm install --production &&
            npm run build &&
            sudo systemctl restart nginx  # Restart Nginx server

