name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check-base-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Check if baseUrl includes localhost
      id: check_base_url
      run: node check-base-url.js

    - name: Proceed if baseUrl is valid
      if: ${{ steps.check_base_url.outcome == 'success' }}
      run: echo "Proceeding with the workflow..."

    - name: Fail if baseUrl includes localhost
      if: ${{ steps.check_base_url.outcome != 'success' }}
      run: |
        echo "baseUrl includes localhost. Failing the job."
        exit 1

    - name: Notify user to check Actions section
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');

          if (context.payload.pull_request) {
            const pr_number = context.payload.pull_request.number;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: "Please check the Actions section after pushing the changes."
            });
          } else {
            const commit_sha = context.sha;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit_sha,
              body: "Please check the Actions section after pushing the changes."
            });
          }
